improve parsing df output
Do not rely on "Avail" wording anymore, but use tail to get the last line written.

Add output check to give a clear error message should reading the space or size doesn't work.

Fixes #2

diff --git a/AppDirSrc/usr/bin/sysrescueusbwriter b/AppDirSrc/usr/bin/sysrescueusbwriter
--- a/AppDirSrc/usr/bin/sysrescueusbwriter
+++ b/AppDirSrc/usr/bin/sysrescueusbwriter
@@ -253,6 +253,10 @@ check_iso()
     fi
 
     declare -g ISOSIZE=$("${BINDIR}/stat" -c %s "$ISOIMAGE")
+    if ! [[ "$ISOSIZE" =~ ^[0-9]+$ ]] ; then
+        echo "ERROR: can't determine iso image size ($ISOSIZE)"
+        exit 3
+    fi
     
     # check md5 checksum that might be embedded in the iso
     # ignore if it is missing but abort if present but not matching
@@ -672,7 +676,12 @@ create_tmpdir()
     fi
     
     # check free space on temp dir
-    TMPSPACE=$("${BINDIR}/df" --block-size=1 --output=avail "$TMPDIR" | "${BINDIR}/grep" -v "Avail")
+    TMPSPACE=$("${BINDIR}/df" --block-size=1 --output=avail "$TMPDIR" | "${BINDIR}/tail" -n 1)
+    if ! [[ "$TMPSPACE" =~ ^[0-9]+$ ]] ; then
+        echo "ERROR: can't determine free space on $TMPDIR ($TMPSPACE)"
+        exit 2
+    fi
+
     # require gracious 50 MB tolerance to account for filesystem metadata and inefficiency
     if [[ "${TMPSPACE}" -lt $[$ISOSIZE+52428800] ]]; then
         echo "ERROR: not enough space on $TMPDIR"
