add --verify-only option

diff --git a/AppDirSrc/usr/bin/sysrescueusbwriter b/AppDirSrc/usr/bin/sysrescueusbwriter
--- a/AppDirSrc/usr/bin/sysrescueusbwriter
+++ b/AppDirSrc/usr/bin/sysrescueusbwriter
@@ -28,6 +28,10 @@ print_help()
     echo "                               Something like /dev/sdb."
     echo "                               A text UI to select a likely device is shown if missing."
     echo ""
+    echo "-i|--verify-only=<DEVICE-PATH> Don't write out the image, but just compare the current"
+    echo "                               content on the given device to the image."
+    echo "                               Can't be used together with -t|--targetdev."
+    echo ""
     echo "-e|--tmpdir=<TMPDIR>           Use the given directory for storing temporary files."
     echo "                               You need enough space there for unpacking the whole"
     echo "                               iso image. Defaults to the TMPDIR environment variable."
@@ -96,11 +100,12 @@ parse_args()
         exit 1
     fi
 
-    local OPTIONS="t:e:g:clh"
-    local LONGOPTS="targetdev:,tmpdir:,grant:,cli,licenses,help"
+    local OPTIONS="t:i:e:g:clh"
+    local LONGOPTS="targetdev:,verify-only:,tmpdir:,grant:,cli,licenses,help"
 
     # option variables as globals, set to default values
     declare -g TARGETDEV=""
+    declare -g VERIFY_ONLY=0
     declare -g ISOIMAGE=""
     declare -g VERBOSE=""
     declare -g GRANT_TOOL=""
@@ -125,7 +130,25 @@ parse_args()
     while true; do
         case "$1" in
             -t|--targetdev)
+                if ! [[ -z "$TARGETDEV" ]]; then
+                    echo "ERROR: -i|--verify_only and -t|--targetdev can't be used together"
+                    print_help
+                    exit 1
+                fi
+
                 TARGETDEV="$2"
+                VERIFY_ONLY=0
+                shift 2
+                ;;
+            -i|--verify-only)
+                if ! [[ -z "$TARGETDEV" ]]; then
+                    echo "ERROR: -i|--verify_only and -t|--targetdev can't be used together"
+                    print_help
+                    exit 1
+                fi
+
+                TARGETDEV="$2"
+                VERIFY_ONLY=1
                 shift 2
                 ;;
             -e|--tmpdir)
@@ -621,6 +644,133 @@ create_tmpdir()
     trap clean_tmpdir EXIT
 }
 
+write_image()
+{
+    if [[ "$CLI" -eq 1 ]] ; then
+        read -p "Are you sure you want to overwrite all content of $TARGETDEV? (y/n)? " answer
+        if [[ "$answer" != "y" ]] && [[ "$answer" != "Y" ]]; then
+            echo "Aborted"
+            exit 1
+        fi
+    else
+        exitcode=0
+        "${BINDIR}/dialog" --erase-on-exit --defaultno --title "Overwriting $TARGETDEV" --yesno \
+            "\nAre you sure you want to overwrite all content of $TARGETDEV?" 8 70 || exitcode=$?
+        if [[ "$exitcode" -ne 0 ]]; then
+            echo "Aborted"
+            exit 1
+        fi
+    fi
+        
+    echo "Partitioning and formatting target device..."
+
+    # size not given means until the end of the device
+    "${BINDIR}/sfdisk" --wipe always --wipe-partitions always --no-tell-kernel --quiet "${TARGETDEV}" 2>/dev/null <<EOF
+label: dos
+unit: sectors
+sector-size: 512
+
+img1 : start=        2048, type=c, bootable
+EOF
+
+    # FAT tools need to convert to/from codepage 850, the dos default
+    # we bring our own gconv libs for our glibc, use them
+    export GCONV_PATH="${APPDIR}/usr/lib/gconv"
+
+    # don't let mtools load any of the systemwide config files
+    export MTOOLSRC="${APPDIR}/mtools.conf"
+    export MCWD="${APPDIR}/mcwd"
+    export MCOPY_SYNC=""
+
+    # the filesystem begins at sector 2048, fix backup boot sector at 6 (see below)
+    "${BINDIR}/mkfs.fat" -F 32 -b 6 -n "${PARTLABEL}" --offset=2048 -I "${TARGETDEV}" >/dev/null
+
+    # copy all files from the iso onto the fat partition
+    declare -a firstlevel
+    readarray -t firstlevel < <("${BINDIR}/find" "${TMPDIR}/filesystem" -maxdepth 1 -mindepth 1)
+
+    if [[ "$CLI" -eq 1 ]] ; then
+        echo "Copying files..."
+        # our patched mcopy outputs the progress to fd 3, one "." per megabyte
+        # regularly flush the buffers for a smooth progress bar (this is part of the mtools patch too)
+        MCOPY_SYNC="\"${BINDIR}/sync\" \"${TARGETDEV}\"" "${BINDIR}/mcopy" -spQm "${firstlevel[@]}" -i "${TARGETDEV}@@1048576" ::/ \
+            3>&1
+        echo
+    else
+        # our patched mcopy outputs the progress to fd 3, one "." per megabyte
+        # regularly flush the buffers for a smooth progress bar (this is part of the mtools patch too)
+        MCOPY_SYNC="\"${BINDIR}/sync\" \"${TARGETDEV}\"" "${BINDIR}/mcopy" -spQm "${firstlevel[@]}" -i "${TARGETDEV}@@1048576" ::/ \
+            3> >("${BINDIR}/gaugeconv" $[$ISOSIZE/1048576] | "${BINDIR}/dialog" --erase-on-exit --gauge "Copying files..." 0 80)
+    fi
+            
+    echo
+    echo "Installing syslinux bootloader..."
+
+    # install syslinux on target dev
+    # forks several mtools programs, so we need to set the PATH to our dir only
+    PATH="${BINDIR}" "${BINDIR}/syslinux" --directory /sysresccd/boot/syslinux/ --install "${TARGETDEV}" --offset 1048576 3>/dev/null
+
+    # install the syslinux MBR, boot from partition 1
+    printf '\1' | "${BINDIR}/cat" "${APPDIR}/usr/lib/syslinux/bios/altmbr.bin" - | "${BINDIR}/dd" bs=440 count=1 iflag=fullblock conv=notrunc "of=${TARGETDEV}" 2>/dev/null
+
+    # syslinux only installs itself to the primary fat boot sector, not the backup boot sector
+    # the backup boot sector is at logical sector 6 of the fat32 filesystem, the primary at sector 1
+    # copy it over so we get a properly clean filesystem
+    "${BINDIR}/dd" bs=512 count=1 iseek=2048 "if=${TARGETDEV}" "of=${TMPDIR}/fatboosect.bin" 2>/dev/null
+    "${BINDIR}/dd" bs=512 count=1 oseek=2054 conv=notrunc,nocreat "if=${TMPDIR}/fatboosect.bin" "of=${TARGETDEV}" 2>/dev/null
+
+    # write all caches to drive before we do verification
+    "${BINDIR}/sync" "${TARGETDEV}"
+}
+
+verify_image()
+{
+    if [[ "$CLI" -eq 1 ]] ; then
+        # pipe "." from mcopy to stdout in cli mode
+        exec 3>&1
+        DIALOGPID=0
+        echo "Verifying data..."
+    else
+        # our patched mcopy outputs the progress to fd 3, one "." per megabyte
+        # run gaugeconv & dialog in the background to display the verification progress
+        exec 3> >("${BINDIR}/gaugeconv" $[$ISOSIZE/1048576] | "${BINDIR}/dialog" --gauge "Verifying data..." 0 80)
+        DIALOGPID=$!
+    fi
+        
+    # verify output media content
+    "${BINDIR}/find" "${TMPDIR}/filesystem/" -type f -printf "%P\n" | while read -r line; do
+        exitcode=0
+        "${BINDIR}/mcopy" -i "${TARGETDEV}@@1048576" "::/${line}" - | \
+            "${BINDIR}/cmp" - "${TMPDIR}/filesystem/${line}" >/dev/null || exitcode=$?
+        if [[ $exitcode -ne 0 ]]; then
+            # end gaugeconv & dialog running in the background by closing it's stdin
+            exec 3>&- || exitcode=$?
+            
+            if [[ "$CLI" -ne 1 ]] ; then
+                wait $DIALOGPID || exitcode=$?
+                
+                # dialog was aborted and messed up the terminal, we need to clean up first
+                "${BINDIR}/stty" sane || exitcode=$?
+                "${BINDIR}/clear"
+            fi
+            
+            echo
+            echo "ERROR: verification mismatch for file ${line}"
+            echo
+            exit 3
+        fi
+    done
+
+    # end gaugeconv & dialog running in the background by closing it's stdin
+    exec 3>&- || exitcode=$?
+
+    if [[ "$CLI" -ne 1 ]] ; then
+        wait $DIALOGPID || exitcode=$?
+        # dialog has ended, but we need to clear the screen
+        "${BINDIR}/clear"
+    fi
+}
+
 ############# SCRIPT STARTS HERE ####################
 
 parse_args "$@"
@@ -646,128 +796,12 @@ echo "Unpacking iso image..."
 
 check_compatibility
 
-if [[ "$CLI" -eq 1 ]] ; then
-    read -p "Are you sure you want to overwrite all content of $TARGETDEV? (y/n)? " answer
-    if [[ "$answer" != "y" ]] && [[ "$answer" != "Y" ]]; then
-        echo "Aborted"
-        exit 1
-    fi
+if [[ $VERIFY_ONLY -eq 0 ]]; then
+    write_image
+    verify_image
 else
-    exitcode=0
-    "${BINDIR}/dialog" --erase-on-exit --defaultno --title "Overwriting $TARGETDEV" --yesno \
-        "\nAre you sure you want to overwrite all content of $TARGETDEV?" 8 70 || exitcode=$?
-    if [[ "$exitcode" -ne 0 ]]; then
-        echo "Aborted"
-        exit 1
-    fi
+    verify_image
 fi
-    
-echo "Partitioning and formatting target device..."
 
-# size not given means until the end of the device
-"${BINDIR}/sfdisk" --wipe always --wipe-partitions always --no-tell-kernel --quiet "${TARGETDEV}" 2>/dev/null <<EOF
-label: dos
-unit: sectors
-sector-size: 512
-
-img1 : start=        2048, type=c, bootable
-EOF
-
-# FAT tools need to convert to/from codepage 850, the dos default
-# we bring our own gconv libs for our glibc, use them
-export GCONV_PATH="${APPDIR}/usr/lib/gconv"
-
-# don't let mtools load any of the systemwide config files
-export MTOOLSRC="${APPDIR}/mtools.conf"
-export MCWD="${APPDIR}/mcwd"
-export MCOPY_SYNC=""
-
-# the filesystem begins at sector 2048, fix backup boot sector at 6 (see below)
-"${BINDIR}/mkfs.fat" -F 32 -b 6 -n "${PARTLABEL}" --offset=2048 -I "${TARGETDEV}" >/dev/null
-
-# copy all files from the iso onto the fat partition
-declare -a firstlevel
-readarray -t firstlevel < <("${BINDIR}/find" "${TMPDIR}/filesystem" -maxdepth 1 -mindepth 1)
-
-if [[ "$CLI" -eq 1 ]] ; then
-    echo "Copying files..."
-    # our patched mcopy outputs the progress to fd 3, one "." per megabyte
-    # regularly flush the buffers for a smooth progress bar (this is part of the mtools patch too)
-    MCOPY_SYNC="\"${BINDIR}/sync\" \"${TARGETDEV}\"" "${BINDIR}/mcopy" -spQm "${firstlevel[@]}" -i "${TARGETDEV}@@1048576" ::/ \
-        3>&1
-    echo
-else
-    # our patched mcopy outputs the progress to fd 3, one "." per megabyte
-    # regularly flush the buffers for a smooth progress bar (this is part of the mtools patch too)
-    MCOPY_SYNC="\"${BINDIR}/sync\" \"${TARGETDEV}\"" "${BINDIR}/mcopy" -spQm "${firstlevel[@]}" -i "${TARGETDEV}@@1048576" ::/ \
-        3> >("${BINDIR}/gaugeconv" $[$ISOSIZE/1048576] | "${BINDIR}/dialog" --erase-on-exit --gauge "Copying files..." 0 80)
-fi
-        
-echo
-echo "Installing syslinux bootloader..."
-
-# install syslinux on target dev
-# forks several mtools programs, so we need to set the PATH to our dir only
-PATH="${BINDIR}" "${BINDIR}/syslinux" --directory /sysresccd/boot/syslinux/ --install "${TARGETDEV}" --offset 1048576 3>/dev/null
-
-# install the syslinux MBR, boot from partition 1
-printf '\1' | "${BINDIR}/cat" "${APPDIR}/usr/lib/syslinux/bios/altmbr.bin" - | "${BINDIR}/dd" bs=440 count=1 iflag=fullblock conv=notrunc "of=${TARGETDEV}" 2>/dev/null
-
-# syslinux only installs itself to the primary fat boot sector, not the backup boot sector
-# the backup boot sector is at logical sector 6 of the fat32 filesystem, the primary at sector 1
-# copy it over so we get a properly clean filesystem
-"${BINDIR}/dd" bs=512 count=1 iseek=2048 "if=${TARGETDEV}" "of=${TMPDIR}/fatboosect.bin" 2>/dev/null
-"${BINDIR}/dd" bs=512 count=1 oseek=2054 conv=notrunc,nocreat "if=${TMPDIR}/fatboosect.bin" "of=${TARGETDEV}" 2>/dev/null
-
-# write all caches to drive before we do verification
-"${BINDIR}/sync" "${TARGETDEV}"
-
-# TODO: add patched version of fsck.vfat that can read from offsets and do a filesystem check
-
-if [[ "$CLI" -eq 1 ]] ; then
-    # pipe "." from mcopy to stdout in cli mode
-    exec 3>&1
-    DIALOGPID=0
-    echo "Verifying data..."
-else
-    # our patched mcopy outputs the progress to fd 3, one "." per megabyte
-    # run gaugeconv & dialog in the background to display the verification progress
-    exec 3> >("${BINDIR}/gaugeconv" $[$ISOSIZE/1048576] | "${BINDIR}/dialog" --gauge "Verifying data..." 0 80)
-    DIALOGPID=$!
-fi
-    
-# verify output media content
-"${BINDIR}/find" "${TMPDIR}/filesystem/" -type f -printf "%P\n" | while read -r line; do
-    exitcode=0
-    "${BINDIR}/mcopy" -i "${TARGETDEV}@@1048576" "::/${line}" - | \
-        "${BINDIR}/cmp" - "${TMPDIR}/filesystem/${line}" >/dev/null || exitcode=$?
-    if [[ $exitcode -ne 0 ]]; then
-        # end gaugeconv & dialog running in the background by closing it's stdin
-        exec 3>&- || exitcode=$?
-        
-        if [[ "$CLI" -ne 1 ]] ; then
-            wait $DIALOGPID || exitcode=$?
-            
-            # dialog was aborted and messed up the terminal, we need to clean up first
-            "${BINDIR}/stty" sane || exitcode=$?
-            "${BINDIR}/clear"
-        fi
-        
-        echo
-        echo "ERROR: verification mismatch for file ${line}"
-        echo
-        exit 3
-    fi
-done
-
-# end gaugeconv & dialog running in the background by closing it's stdin
-exec 3>&- || exitcode=$?
-
-if [[ "$CLI" -ne 1 ]] ; then
-    wait $DIALOGPID || exitcode=$?
-    # dialog has ended, but we need to clear the screen
-    "${BINDIR}/clear"
-fi
-    
 echo
 echo "Success"
